### ISSUE TITLE
invalid time string

### ISSUE THREAD

**Issue by paviro** [benleb/ad-automoli#70]
😩 **Describe the issue/bug**
After updating to the latest version in HACS all my sensors stopped working.

🎛️ **Configuration**
```yaml
wohnzimmer_bewegungsmelder:
  module: automoli
  class: AutoMoLi
  room: Wohnzimmer
  delay: 300
  daytimes:
    - { starttime: "04:30", name: morning, light: "scene.wohnzimmer_morgens" }
    - { starttime: "sunrise-01:00", name: sunrise, light: "scene.wohnzimmer_kunstlicht" }
    - { starttime: "sunrise+01:00", name: daylight, light: "scene.wohnzimmer_tageslicht" }
    - { starttime: "sunset-00:30", name: evening, light: "scene.wohnzimmer_kunstlicht" }
    - { starttime: "20:00", name: relaxed, light: "scene.wohnzimmer_entspannend" }
    - { starttime: "00:00", name: night, light: "scene.wohnzimmer_nacht", delay: 180 }

  illuminance: sensor.wohnzimmer_helligkeit_mean
  illuminance_threshold: 45 
  
  disable_switch_entities:
    - input_boolean.bewegungsmelder
    - input_boolean.bewegungsmelder_wohnzimmer
  disable_switch_states: "off"

  motion_state_on: "on"
  motion_state_off: "off"
  motion:
    - binary_sensor.wohnzimmer_sofa_bewegung
    - binary_sensor.kuche_bewegung
    - binary_sensor.wohnzimmer_treppe_bewegung
    - binary_sensor.flur_eg_bewegung
    - binary_sensor.wohnzimmer_esstisch_bewegung
    - input_boolean.wohnzimmer_presence_overwrite
    - switch.fernseher

  dim:
    method: transition
    seconds_before: 10
    
  only_own_events: false
  transition_on_daytime_switch: true
```

🧠 **System**
 - AppDaemon: **[e.g. 4.0.5]** 0.5.0 (Latest available in HASS)
   -  running mode: **[e.g. virtualenv, hassio-plugin, docker]** hassio-plugin
 - Home-Assistant: **[e.g. 0.118.3, 0.119.0b0]** latest
   -  running mode: **[e.g. virtualenv, hassio, docker]** hassio

🗒️ **Logs** 

```log
2021-03-28 16:29:34.972933 WARNING wohnzimmer_bewegungsmelder: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/app_management.py", line 159, in initialize_app
    await init()
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 330, in initialize
    daytimes = await self.build_daytimes(self.args.pop("daytimes", DEFAULT_DAYTIMES))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 925, in build_daytimes
    if await self.now_is_between(str(dt_start), str(next_dt_start)):
  File "/usr/lib/python3.8/site-packages/appdaemon/adapi.py", line 2077, in now_is_between
    return await self.AD.sched.now_is_between(start_time, end_time, name)
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 699, in now_is_between
    end_time = (await self._parse_time(end_time_str, name))["datetime"]
  File "/usr/lib/python3.8/site-packages/appdaemon/scheduler.py", line 802, in _parse_time
    raise ValueError("invalid time string: %s", time_str)
ValueError: ('invalid time string: %s', '06:21:33.896572')
```

**Comment by benleb** [comment]
hmmm seems appdaemon doesn't like microseconds... give me a second...

**Comment by benleb** [comment]
should work now, tell me if not :)

**Comment by paviro** [comment]
Seems to work but probably unrelated:
```
2021-03-28 17:49:01.050769 WARNING flur_eg_bewegungsmelder: Unexpected error in worker for App flur_eg_bewegungsmelder:
2021-03-28 17:49:01.052218 WARNING flur_eg_bewegungsmelder: Worker Ags: {'id': 'd538e4882dc8435792fbca0e19ccb3cc', 'name': 'flur_eg_bewegungsmelder', 'objectid': '5a59ca84efce4146b66df2ffd90cd899', 'type': 'scheduler', 'function': <bound method AutoMoLi.lights_off of <automoli.AutoMoLi object at 0x7f97021610>>, 'pin_app': True, 'pin_thread': 8, 'kwargs': {'__thread_id': 'MainThread'}}
2021-03-28 17:49:01.053609 WARNING flur_eg_bewegungsmelder: ------------------------------------------------------------
2021-03-28 17:49:01.055155 WARNING flur_eg_bewegungsmelder: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 801, in async_worker
    await funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 796, in lights_off
    await self.clear_handles(deepcopy(self.handles))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 529, in clear_handles
    *[self.cancel_timer(handle) for handle in handles if await self.timer_running(handle)]
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 529, in <listcomp>
    *[self.cancel_timer(handle) for handle in handles if await self.timer_running(handle)]
AttributeError: 'AutoMoLi' object has no attribute 'timer_running'
2021-03-28 17:49:01.058631 WARNING flur_eg_bewegungsmelder: ------------------------------------------------------------
2021-03-28 17:49:01.066552 WARNING flur_og_bewegungsmelder: ------------------------------------------------------------
2021-03-28 17:49:01.067992 WARNING flur_og_bewegungsmelder: Unexpected error in worker for App flur_og_bewegungsmelder:
2021-03-28 17:49:01.069198 WARNING flur_og_bewegungsmelder: Worker Ags: {'id': 'd14ac0856b5e4777b99d743a3a40c750', 'name': 'flur_og_bewegungsmelder', 'objectid': '633a3d60b2914d2cb4a4091249293c93', 'type': 'scheduler', 'function': <bound method AutoMoLi.lights_off of <automoli.AutoMoLi object at 0x7f95d83820>>, 'pin_app': True, 'pin_thread': 9, 'kwargs': {'__thread_id': 'MainThread'}}
2021-03-28 17:49:01.070457 WARNING flur_og_bewegungsmelder: ------------------------------------------------------------
2021-03-28 17:49:01.072057 WARNING flur_og_bewegungsmelder: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 801, in async_worker
    await funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 796, in lights_off
    await self.clear_handles(deepcopy(self.handles))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 529, in clear_handles
    *[self.cancel_timer(handle) for handle in handles if await self.timer_running(handle)]
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 529, in <listcomp>
    *[self.cancel_timer(handle) for handle in handles if await self.timer_running(handle)]
AttributeError: 'AutoMoLi' object has no attribute 'timer_running'
```

Let me know if I should open a new issue for this.

**Comment by benleb** [comment]
ah fuck... `timer_running` is a feature which will be introduced in upcoming appdaemon 4.0.7 and the hassio addon uses (the still stable) 4.0.6 😵‍💫 mom...^^

**Comment by paviro** [comment]
Damn I can also upgrade to the 4.0.7 beta

**Comment by benleb** [comment]
nope, I pushed a fix right now :) should work with appdaemon <= 4.0.7 now (requiring a beta version is not my intention 😅)

**Comment by paviro** [comment]
I still get the same error:
```2021-03-28 19:38:26.892849 WARNING schlafzimmer_bewegungsmelder: ------------------------------------------------------------
2021-03-28 19:38:26.895523 WARNING schlafzimmer_bewegungsmelder: Unexpected error in worker for App schlafzimmer_bewegungsmelder:
2021-03-28 19:38:26.897073 WARNING schlafzimmer_bewegungsmelder: Worker Ags: {'id': 'b1df8d8c812a409cb446ef0dc90a1660', 'name': 'schlafzimmer_bewegungsmelder', 'objectid': 'f9bbf1c9c50449dea5d995314100b0f8', 'type': 'state', 'function': <bound method AutoMoLi.motion_detected of <automoli.AutoMoLi object at 0x7f97021430>>, 'attribute': 'state', 'entity': 'binary_sensor.schlafzimmer_bett_bewegung', 'new_state': 'on', 'old_state': 'off', 'pin_app': True, 'pin_thread': 6, 'kwargs': {'new': 'on', '__thread_id': 'MainThread'}}
2021-03-28 19:38:26.898443 WARNING schlafzimmer_bewegungsmelder: ------------------------------------------------------------
2021-03-28 19:38:26.899973 WARNING schlafzimmer_bewegungsmelder: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 812, in async_worker
    await funcref(
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 477, in motion_detected
    await self.clear_handles(deepcopy(self.handles))
  File "/config/appdaemon/apps/ad-automoli/automoli.py", line 529, in clear_handles
    if self.timer_running:
AttributeError: 'AutoMoLi' object has no attribute 'timer_running'
```

**Comment by benleb** [comment]
okay, removed the 4.0.7 code... will reactivate it when 4.0.7 is released as stable :)

**Comment by paviro** [comment]
Looks good 👍🏼 Will test night mode probably around April 10th I am not at home until then :/
